# Continuous Delivery/Deployment to DockerHub
name: cd

on:
  workflow_run:
    workflows:
      - create-release
    types:
      - completed

  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
      # https://semver.org/ proper release tags, more or less
      - 'v[0-9]+.[0-9]+.[0-9]+'
      # prerelease tags, more or less
      - 'v[0-9]+.[0-9]+.[0-9]+-*'

jobs:
  dockerhub:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: check out a copy of the repo
        uses: actions/checkout@v2

      - name: Install Task
        uses: arduino/setup-task@v1

      - name: set up qemu
        uses: docker/setup-qemu-action@v1

      - name: set up docker buildx
        uses: docker/setup-buildx-action@v1

      - name: login to dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Images Docker
        run: task push:docker
